---
label: default
hide_body: true
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: 2_column_layout
  type: field_group
  config: {}
  fields:
  - name: column_1_group
    type: field_group
    config: {}
    fields:
    - name: type
      type: select
      default: []
      config:
        required: false
        options:
        - Text
        - image
        - video
        source:
          type: simple
          section: 
          file: 
          path: 
      label: Type
    - name: text
      type: textarea
      default: ''
      config:
        required: false
        wysiwyg: true
        schema:
          format: markdown
      label: Text
    label: Column 1
  - name: column_2
    type: field_group
    config: {}
    fields:
    - name: type
      type: select
      default: []
      config:
        required: false
        options:
        - Text
        - Image
        - Video
        - Wide-Image
        source:
          type: simple
          section: 
          file: 
          path: 
      label: Type
    - name: image
      type: file
      config:
        maxSize: 250
      label: Image
    label: Column 2
  label: 2 Column layout
pages:
- content/about.html
