---
label: default
hide_body: true
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: 2_column_layout
  type: field_group
  config: {}
  fields:
  - name: column_1_group
    type: field_group
    config: {}
    fields:
    - name: type
      type: select
      default: []
      config:
        required: false
        options:
        - Text
        - image
        - video
        source:
          type: simple
          section: 
          file: 
          path: 
      label: Type
    label: Column 1
  - name: column_2
    type: select
    default: []
    config:
      required: false
      options:
      - Text
      - Video
      - Image
      source:
        type: simple
        section: 
        file: 
        path: 
    label: Column 2
  label: 2 Column layout
pages:
- content/about.html
