---
label: default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: banner
  type: file
  config:
    maxSize: 250
  label: Banner
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: type
  type: select
  default: []
  config:
    required: false
    options:
    - image
    - video
    - text
    - heading
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
- name: test_group
  type: field_group
  config: {}
  label: Test Group
- name: 2_column_layout
  type: field_group
  config: {}
  fields:
  - name: column_1
    type: select
    default: []
    config:
      required: false
      options:
      - Text
      - Video
      - Image
      - Title
      source:
        type: simple
        section: 
        file: 
        path: 
    label: Column 1
  - name: column_2
    type: select
    default: []
    config:
      required: false
      options:
      - Title
      - Text
      - Video
      - Image
      source:
        type: simple
        section: 
        file: 
        path: 
    label: Column 2
  label: 2 Column layout
pages:
- content/about.html
