---
label: default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: banner
  type: file
  config:
    maxSize: 250
  label: Banner
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: type
  type: select
  default: []
  config:
    required: false
    options:
    - image
    - video
    - text
    - heading
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
pages:
- content/about.html
